# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_linux32
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
DEFINES +=
INCLUDES += -I.
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_linux32)
TARGETDIR = ../../bin/Debug/linux/x86
TARGET = $(TARGETDIR)/fasm
OBJDIR = ../../obj/Debug/linux/x86/Linux32/Debug/FalconASMBin
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g -std=c++17
LIBS += ../../lib/Debug/linux/x86/libFalconASM.a
LDDEPS += ../../lib/Debug/linux/x86/libFalconASM.a
ALL_LDFLAGS += $(LDFLAGS) -L../../lib/Debug/linux/x86 -L/usr/lib32 -m32

else ifeq ($(config),debug_linux64)
TARGETDIR = ../../bin/Debug/linux/x86_64
TARGET = $(TARGETDIR)/fasm
OBJDIR = ../../obj/Debug/linux/x86_64/Linux64/Debug/FalconASMBin
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c++17
LIBS += ../../lib/Debug/linux/x86_64/libFalconASM.a
LDDEPS += ../../lib/Debug/linux/x86_64/libFalconASM.a
ALL_LDFLAGS += $(LDFLAGS) -L../../lib/Debug/linux/x86_64 -L/usr/lib64 -m64

else ifeq ($(config),release_linux32)
TARGETDIR = ../../bin/Release/linux/x86
TARGET = $(TARGETDIR)/fasm
OBJDIR = ../../obj/Release/linux/x86/Linux32/Release/FalconASMBin
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O3
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O3 -std=c++17
LIBS += ../../lib/Release/linux/x86/libFalconASM.a
LDDEPS += ../../lib/Release/linux/x86/libFalconASM.a
ALL_LDFLAGS += $(LDFLAGS) -L../../lib/Release/linux/x86 -L/usr/lib32 -m32 -s

else ifeq ($(config),release_linux64)
TARGETDIR = ../../bin/Release/linux/x86_64
TARGET = $(TARGETDIR)/fasm
OBJDIR = ../../obj/Release/linux/x86_64/Linux64/Release/FalconASMBin
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O3
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -std=c++17
LIBS += ../../lib/Release/linux/x86_64/libFalconASM.a
LDDEPS += ../../lib/Release/linux/x86_64/libFalconASM.a
ALL_LDFLAGS += $(LDFLAGS) -L../../lib/Release/linux/x86_64 -L/usr/lib64 -m64 -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/test.o
OBJECTS += $(OBJDIR)/test.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking FalconASMBin
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning FalconASMBin
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/test.o: test/test.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif