name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: .

jobs:
  build_linux:
    defaults:
      run:
        shell: bash
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./premake5/premake5 gmake2
    - name: build64
      run: make config=release_linux64
  
  build_windows:
    defaults:
      run:
        shell: cmd
    
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: premake5\premake5.exe vs2019
      - name: build64
        run: |
          call "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2019\Visual Studio Tools\Developer Command Prompt for VS 2019.lnk"
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\"
          MSBuild.exe Falcon.sln /p:Configuration=Release|Win64
